### ISSUE TITLE
error on  the transfer learning step

### ISSUE THREAD

**Issue by helianthuszhu** [OSU-BMBL/scDEAL#1]
Hi Junyi,

     Lucky to see the scDEAL pipeline which is potentially useful for my drug associated scRNA data.
     Here, I am trying the pipeline on my dataset. The bulkmode.py step can be successfully finished with the output in the 'save/bulk_pre/' or 'save/bulk_encoder/' and ROC.pdf. However, when it comes to the scmodel.py step, something goes wrong as below. Any suggestions on this would be appreciated. Thank you very much.
#step1 (can finish)
python bulkmodel.py --data './data/tnfa_batched_after/expM_batched.csv' \
--label './data/tnfa_batched_after/clin_batched.csv' \
--data_name 'GSEbatch' \
--result './save/results/result_' --drug 'TNFA' \
--dimreduce 'AE' --encoder_h_dims "256,256" --predictor_h_dims "128,64" \
--bottleneck 256 --sampling 'SMOTE' --dropout 0.3 --printgene 'F' -mod 'new'
#
#step2
python scmodel.py --bulk_data './data/expM_batched.csv' \
--label './data/clin_batched.csv' \
--sc_data '/data/adata_rawcount_matrix.csv' \
--bulk_model_path 'save/bulk_pre' \
--pretrain 'save/sc_encoder' \
--dimreduce 'AE' --drug 'TNFA'  \
--percent_mito 10 \
--bulk_h_dims "256,256" --bottleneck 256 --predictor_h_dims "128,64" --dropout 0.3 --printgene 'F' -mod 'new' 
#error
Traceback (most recent call last):
  File "scmodel.py", line 794, in <module>
    run_main(args)
  File "scmodel.py", line 302, in run_main
    para = args.bulk+"_data_"+args.sc_data+"_drug_"+args.drug+"_bottle_"+str(args.bottleneck)+"_edim_"+args.bulk_h_dims+"_pdim_"+args.predictor_h_dims+"_model_"+reduce_model+"_dropout_"+str(args.dropout)+"_gene_"+args.printgene+"_lr_"+str(args.lr)+"_mod_"+args.mod+"_sam_"+args.sampling
TypeError: can only concatenate str (not "NoneType") to str
####
I also tried to input the scRNA matrix from your example, like GSE112274_cell_gene_FPKM.csv, but the same error occured.

**Comment by FLabbaf97** [comment]
Hello, 
were you able to solve this problem?

**Comment by gwyang6** [comment]
Hello, thank you very much for your project. I have encountered the same problem. Can you solve it?

**Comment by juychen** [comment]
Hi, I have updated the code accordingly

> Hello, thank you very much for your project. I have encountered the same problem. Can you solve it?



> Hello, were you able to solve this problem?



> Hi Junyi,
> 
> ```
>  Lucky to see the scDEAL pipeline which is potentially useful for my drug associated scRNA data.
>  Here, I am trying the pipeline on my dataset. The bulkmode.py step can be successfully finished with the output in the 'save/bulk_pre/' or 'save/bulk_encoder/' and ROC.pdf. However, when it comes to the scmodel.py step, something goes wrong as below. Any suggestions on this would be appreciated. Thank you very much.
> ```
> 
> #step1 (can finish) python bulkmodel.py --data './data/tnfa_batched_after/expM_batched.csv' --label './data/tnfa_batched_after/clin_batched.csv' --data_name 'GSEbatch' --result './save/results/result_' --drug 'TNFA' --dimreduce 'AE' --encoder_h_dims "256,256" --predictor_h_dims "128,64" --bottleneck 256 --sampling 'SMOTE' --dropout 0.3 --printgene 'F' -mod 'new'
> 
> #step2 python scmodel.py --bulk_data './data/expM_batched.csv' --label './data/clin_batched.csv' --sc_data '/data/adata_rawcount_matrix.csv' --bulk_model_path 'save/bulk_pre' --pretrain 'save/sc_encoder' --dimreduce 'AE' --drug 'TNFA' --percent_mito 10 --bulk_h_dims "256,256" --bottleneck 256 --predictor_h_dims "128,64" --dropout 0.3 --printgene 'F' -mod 'new' #error Traceback (most recent call last): File "scmodel.py", line 794, in run_main(args) File "scmodel.py", line 302, in run_main para = args.bulk+"_data_"+args.sc_data+"_drug_"+args.drug+"_bottle_"+str(args.bottleneck)+"_edim_"+args.bulk_h_dims+"_pdim_"+args.predictor_h_dims+"_model_"+reduce_model+"_dropout_"+str(args.dropout)+"_gene_"+args.printgene+"_lr_"+str(args.lr)+"_mod_"+args.mod+"_sam_"+args.sampling TypeError: can only concatenate str (not "NoneType") to str
> 
> I also tried to input the scRNA matrix from your example, like GSE112274_cell_gene_FPKM.csv, but the same error occured.
