### ISSUE TITLE
Unable to successfully download ALL_label_binary_wf.csv and ALL_expression.csv

### ISSUE THREAD

**Issue by mingjiang7940** [OSU-BMBL/scDEAL#14]
Hi juychen，

I am very interested in the software you developed. When I wanted to download the demo data, I was told, "This item might not exist or is no longer available". Can you provide me with these two files([ALL_label_binary_wf.csv](https://portland-my.sharepoint.com/personal/junyichen8-c_my_cityu_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjunyichen8%2Dc%5Fmy%5Fcityu%5Fedu%5Fhk%2FDocuments%2FscDEAL%2F0319%2FscDEAL%2Ezip&parent=%2Fpersonal%2Fjunyichen8%2Dc%5Fmy%5Fcityu%5Fedu%5Fhk%2FDocuments%2FscDEAL%2F0319&ga=1),[ALL_expression.csv](https://portland-my.sharepoint.com/personal/junyichen8-c_my_cityu_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjunyichen8%2Dc%5Fmy%5Fcityu%5Fedu%5Fhk%2FDocuments%2FscDEAL%2F0319%2FscDEAL%2Ezip&parent=%2Fpersonal%2Fjunyichen8%2Dc%5Fmy%5Fcityu%5Fedu%5Fhk%2FDocuments%2FscDEAL%2F0319&ga=1))?

thank you!

best,
Cheng

**Comment by juychen** [comment]
https://portland-my.sharepoint.com/:u:/g/personal/junyichen8-c_my_cityu_edu_hk/ER2m5OXpYrdPngoAf06pqDoBsiuItm9yvAqg_CjHhNvKSA?e=ckLJ91

Hi, they should be in the zip file here

**Comment by mingjiang7940** [comment]
My issue has been resolved. Thank you!
