### ISSUE TITLE
Cannot find ‘output model‘ in the directory ’saved/models. ‘ 

### ISSUE THREAD

**Issue by CunJ1n** [OSU-BMBL/scDEAL#2]
Dear Professor Chen：
  Thank you very much for your new method, which has brought me new ideas, but I did not see the expected results when running the program. The file is prepared to be consistent with your tutorial and run according to the sample code. However, in bulkmode.py step , only "two databases combine" is returned, I cannot find ‘output model‘ in the directory ’saved/models. ‘ Any suggestions on this would be appreciated. Thank you very much.

`python bulkmodel.py --drug 'I-BET-762' --dimreduce 'AE' --encoder_h_dims "256,256" --predictor_h_dims "128,64" --bottleneck 256 --data_name 'GSE110894' --sampling 'SMOTE' --dropout 0.3 --printgene 'F' -mod 'new'`

`two databases combine `

**Comment by juychen** [comment]
Hi, we have edited the code to fix this. Thanks
